<a href="https://colab.research.google.com/github/Castleexe/Capstone/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors


*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar To Numpy Arrays, but full of fun things taht make them work better on GPU's (vs regular CPU's)
*   default data type of float 32
*   More suitable for deep learning than a numpy array

Tensors basically hold your data when doing deep learning


In [3]:
import torch
import numpy as np

# Lists

In [2]:
#basic lists in python
my_list = [[1,2,3,4,5], [6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

# Numpy arrays


In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.15652452, 0.99959835, 0.41519344, 0.57354243],
       [0.81434186, 0.211635  , 0.06606995, 0.81424433],
       [0.7737919 , 0.57633944, 0.88954085, 0.73223005]])

In [5]:
np1.dtype

dtype('float64')

# Tensors


In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.6335, -0.3807,  2.0340,  1.4533],
        [-0.1860,  1.6052, -0.4974, -1.5890],
        [ 0.7367, -0.5785, -0.6595,  0.3094]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1565, 0.9996, 0.4152, 0.5735],
        [0.8143, 0.2116, 0.0661, 0.8142],
        [0.7738, 0.5763, 0.8895, 0.7322]], dtype=torch.float64)