<a href="https://colab.research.google.com/github/Castleexe/Capstone/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Math Operations


*   Add, subtract, multiply, divide, remainders, exponents
*   Shorthand and longhand
*   Reassignment




In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
#Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
#Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
#Div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
#Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [4]:
#Remainder longland
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [5]:
#Exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [6]:
#another way to write longhand
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
#reassignment_
tensor_a + tensor_b

tensor([11, 14, 17, 20])

In [ ]:
tensor_a

In [ ]:
#tensor_a = tensor_a + tensor_b

In [8]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [9]:
tensor_a

tensor([11, 14, 17, 20])